### ISSUE TITLE
UI 스타일에 관하여

### ISSUE THREAD

**Issue by vlaksuga** [vlaksuga/newcrm#10]
type 1. JSON COMAPNY
![image](https://user-images.githubusercontent.com/45654321/63917672-193eab80-ca76-11e9-9bc5-345cac6c2b22.png)

type 2. CIRCLE CI MODEL
![image](https://user-images.githubusercontent.com/45654321/63917840-75a1cb00-ca76-11e9-9b34-897e9c2c2d5d.png)

2번이 좋다고 생각함

**Comment by mufasakang** [comment]
2번이 좋음

**Comment by vlaksuga** [comment]
2번스타일로
