### ISSUE TITLE
잦은 ACCOUNT 로그인에 관하여

### ISSUE THREAD

**Issue by vlaksuga** [vlaksuga/newcrm#11]
### ASIS
CASE
로또리치는 광고주다.
로또리치1과 로또리치2는 ACCOUNT라고 정의한다.
로또리치1과 로또리치2는 각각 ID/PW가 있다.
로또리치1과 로또리치2의 DB데이터를 확인하기 위해서 2번의 로그인이 필요하다.
로또리치1과 로또리치2를 분리해서 사용하는 이유는
1. 광고를 송출하는 곳이 다르다.
2. 수집한 DB의 활용을 달리하고 싶다. (EX. DB를 활용하는 사람이 다른경우)
3. 구좌의 추가 등으로 기존 광고효과와 비교하고 싶다.
등이 있다.

### TOBE
로또리치를 ACCOUNT라고 재정의한다.
로또리치가 ACCOUNT인 USER이므로 ID/PW를 갖는다.
로또리치1과 로또리치2는 CHANNEL이라고 정의한다.
로또리치1과 로또리치2는 ID/PW가 없다.
로또리치1과 로또리치2의 DB데이터를 확인하기 위해서 1번의 로그인이면 된다.

**Comment by mufasakang** [comment]
![image](https://user-images.githubusercontent.com/48310497/63940303-270b2580-caa4-11e9-9d0d-e7fb3fd0696c.png)

이미지와 같이, 1,2, 따로 볼수도 있고, 통합으로도 볼수 있게 한다

**Comment by vlaksuga** [comment]
각 채널별로 볼 수 있고, 모든 채널의 합을 볼 수 있다.
1,2 따로 보기 기능은 지원하지 않는다.
