### ISSUE TITLE
AGENCY의 입장에서

### ISSUE THREAD

**Issue by vlaksuga** [vlaksuga/newcrm#12]
### ASIS
1개 이상의 ACCOUNT를 관리하는 자를 AGENCY라고 정의한다.
AGENCY가 ACCOUNT를  관리하기 위해서 ACCOUNT ID/PW를 개별 관리한다.
관리하는 ACCOUNT를 통합적으로 열람/관리할 수 없으므로 로그인-아웃이 빈번하게 발생한다.

### TOBE
1개 이상의 CHANNEL을 관리하는 자를 AGENCY로 재정의한다.
AGENCY가 CHANNEL을 관리하기 위해서 AGENCY ID/PW를 입력한다.
관리 권한이 부여된 CHANNEL을 통합적으로 열람/관리한다.

**Comment by mufasakang** [comment]
확인
