### ISSUE TITLE
한개의 광고주 2명의 관리자일때

### ISSUE THREAD

**Issue by vlaksuga** [vlaksuga/newcrm#13]
### ASIS
ACCOUNT만 USER 이므로 복수의 AGENCY가 ACCOUNT ID를 사용함.
CASE.
로또리치는 이엠스타 김철수와 블랙슈가 강지형이 열람한다.
모두 로또리치 계정을 이용한다.

### TOBE
ACCOUNT가 생성한 CHANNEL을 다수의 AGENCY가 공유함
2명이상의 AGENCY에게 관리 권한이 있는 CHANNEL의 경우 DB의 삭제, 가공 등에 대한 권한은
누가 갖는가를 생각해봐야 함.

**Comment by mufasakang** [comment]
한개의 CHANNEL에는 한개의 AGENCY만 존재한다.
AGENCY와 AE는 각자의 계정에서 해당CHANNEL을 확인할수 있다.
DB가공데 대한 권한은 AGENCY가 기본으로 갖는다. (#9 의 코멘트의 3번과 겹치는 내용

**Comment by vlaksuga** [comment]
CHANNEL을 중심으로 해당 채널에 연결되어 있는 USER는 USERTYPE에 맞는 권한으로 채널을 열람 또는 정한다.
