### ISSUE TITLE
여러명의 상담사를 두고 있는 광고주에 관하여

### ISSUE THREAD

**Issue by vlaksuga** [vlaksuga/newcrm#14]
### ASIS
당에이스는 3명의 상담사를 운영하고 있다.
당에이스1, 당에이스2, 당에이스3은 각각 ACCOUNT다.
당에이스1-TM1, 당에이스2-TM2, 당에이스3-TM3에게 맡기고 있다.
TM2가 결혼해서 퇴사했다.
당에이스1, 당에이스3은 살리고 당에이스2의 기존의 DB는 회사에서 솔루션 내에서 해결할 수 없다.

### TOBE
당에이스는 3명의 상담사를 운영하고 있다.
당에이스는 상담사 분배 목적이외에는 광고 분배 이유가 없다.
TM1, TM2, TM3는 각각 ID/PW를 갖는 USER이다.
TM1, TM2, TM3에게 CHANNEL을 연결한다.

1. 1 CHANNEL 다수 TM일경우 : 누가 먼저 해도 상관없다고 판단할때
2. 1 CHANNEL 다수 TM일경우 : 들어오는 순서대로 배분해주고 싶을 때 (자세한 이슈 추가)
3. 각각 CHANNEL에 각각의 TM일경우 : CHANNEL에 대해서 독점 권한을 갖기를 원할때

TM2가 권한을 말소하면
1일때 문제없음.
2일때 분배규칙 변경
3일때 CHANNEL내에 속한 DB를 CHANNEL 변경

**Comment by vlaksuga** [comment]
CHANNEL내에 속한 DB를 변경할때 기존의 DB를 복사형태로 할지, 이동형태로 할지 생각해볼것.

**Comment by mufasakang** [comment]
이동형태

**Comment by vlaksuga** [comment]
CHANNEL에 연결된 MK가 주문권한을 말소하면, 분배된 주문은 해당 MK를 제외하고 재분배된다.
