### ISSUE TITLE
건강식품 회사 등에 대해서 발생할 문제에 관하여

### ISSUE THREAD

**Issue by vlaksuga** [vlaksuga/newcrm#15]
### ASIS
A 건강식품회사는 당에이스도 팔고, 관절염약도 팔고, 다이어트 약도 판다.
A 건강식품회사는 당에이스, 관절에이스, 다이어트에이스의 3개의 어카운트가 있다.
A 건강식품회사는 상담직원이 갑, 을, 병 3명이다.
DB분배문제가 복잡해지고 받은 DB를 회사내에서 재분배한다.

### TOBE
A 건강식품회사로 ACCOUNT를 생성하여 3개의 CHANNEL을 생성한다.
CHANNEL에 상담직원의 권한을 부여하여 해당 DB중 특정 RECORD에 상담결과 등이 저장되면
회사는 각 상담직원의 성과를 분석할 수 있다.

**Comment by mufasakang** [comment]
company-boss-Mboss-TM 로 순을 정하고
1개의 TM은 1개의 Mboss만 갖는다. 
1개의 Mboss는 1개의 boss만 갖는다.

company는 1개 (광고주)
boss는 복수 (당이에스,관절약,다이어트등)
Mboss 복수 (1팀,2팀,3팀)
TM 복수

**Comment by vlaksuga** [comment]
1개의 Mboss는 1개의 boss만 갖지 않는다

**Comment by mufasakang** [comment]
_BOSS마다 운영하는 팀이 다를경우에는 1개의 MBOSS는 1개의 BOSS만 가져야 할것 같습니다._
라고 생각했으나, '1개의 MBOSS는 다수의 BOSS를 가질수 있다'로 정정하면 될듯

**Comment by vlaksuga** [comment]
MBOSS 등이 없어짐.
