### ISSUE TITLE
AGENCY의 세분화의 가능성에 관하여

### ISSUE THREAD

**Issue by vlaksuga** [vlaksuga/newcrm#16]
AGENCY가 블랙슈가 사람인 경우와 외부인인 경우 분리해야 하는가
분리해야한다면 어떤 기능적 차이가 있어야 하는가.

**Comment by mufasakang** [comment]
AGENCY는 외부
AE는 내부로 규정을 한다. 권한등은 #9 #13 코멘트와 겹치는 내용

**Comment by vlaksuga** [comment]
AGENCY로 통합함
