### ISSUE TITLE
도메인을 정합시다 #6번과 관련

### ISSUE THREAD

**Issue by mufasakang** [vlaksuga/newcrm#17]
이슈들을 정리하며, 회의를 하며.. 도메인이 계속 섞이거나 변경되는데
실제에선 그 도메인이 활용이 되든 안되는 우선 도메인은 정해야 된다고 생각함
지금까지 거론된 이름들
(ADMIN, AGENCY, BOSS, MBOSS, ACCOUNT,AE,TM,CHANNEL,COMPANY)

- ADMIN -> 블랙슈가 관리자
- COMPANY -> 광고주
- BOSS -> 광고주의 어카운트
- AGENCY -> 광고대행사 (외부)
- MBOSS -> 중간관리자
- AE -> 광고대행사 (블랙슈가)
- TM -> 광고주의 말단직원
- CHANNEL -> DB의 집합소

추가할 내용이나 단어 및 내용에 대한 의견 다시오.

**Comment by vlaksuga** [comment]
USER
ADMIN / BOSS / AGENCY / MBOSS / AE / TM
인가요

**Comment by mufasakang** [comment]
User->ID/PW가 있는것
User : ADMIN, COMPANY, AGENCY, MBOSS, AE, TM
입니다. BOSS는 COMPANY에 종속되는 어카운트라 BOSS가 하나라면 COMPANY에는 한개만 노출이 됩니다.

**Comment by vlaksuga** [comment]
User->ID/PW가 있는것
User : ADMIN / OWNER / AGENCY / MK
