### ISSUE TITLE
DB 삭제하는 기능 추가

### ISSUE THREAD

**Issue by vlaksuga** [vlaksuga/newcrm#4]
1. 삭제는 누가하는가
2. 삭제된 DB는 어떻게 처리하는가
3. 삭제된 DB는 복구 가능한가
4. 누구에게 권한이 있는가 등등

**Comment by mufasakang** [comment]
기본구조 (최고관리자-중간관리자-일반)
1. 중간관리자 이상
2. 원칙적으로 삭제는 불가. 즉 중간관리자 이상급이 '비활성화'처리함
3. '비활성화'를 '활성화'로 변경함
4. 1번과 동일

최고관리자는 중간관리자들의 관리계정을 볼수 있고, 권한은 최고,중간관리자 동일

**Comment by vlaksuga** [comment]
삭제 기능은 없다.
owner가 mask하기 기능으로 해당 주문을 안보이게 처리하고, 되돌리기 처리한다
통계에 영향을 주지 않는다.
