### ISSUE TITLE
중복 DB의 처리

### ISSUE THREAD

**Issue by vlaksuga** [vlaksuga/newcrm#5]
1. 중복 DB의 정의 (이름 일치, 전화번호 일치, 둘다 일치 등)
2. 중복 DB의 기한 (한번 남긴 DB는 영원히 한번인가, 재 문의는 어떻게 처리하는가)
3. 중복 DB는 DB로 남기는가, 누구에게 보여주는가.

**Comment by akamoovon** [comment]
1. 전화번호 일치의 경우만 중복DB로 간주함.
2. 1년.
3. 자동으로 모두에게 에러현황에 보여짐.

**Comment by vlaksuga** [comment]
전화번호 일치일 경우 생각해봐야 할 2가지 문제
1. 전화번호는 숫자로만 입력받아서 동일성을 확보한다.
2. 1년에 전화번호가 변경된 다른 사람이 DB를 남기게 되면 중복처리되어 실제 신규 DB라고 할지라도 무시당함을 인지한다.

1 의 경우 랜딩페이지 작성시에 무조건 숫자로 받는데만 동의해야함
2의 경우 광고주가 동의할 수 있으면 문제는 없다고 생각함.

**Comment by mufasakang** [comment]
1. 동일IP 추가. 이름과 전화번호등 속성일치에 대해선 and,or등으로 설정할수 있음
중복DB에 대한 필요속성-이름,전화번호,ip,영역번호,
2. 사용자에게 기간설정을 할수 있게함(기간은 당일부터),1차 기간설정 2차 기간설정으로 함
3. 첫번째 항목(이 무엇이든)에 색채움등으로 표기함. 표기는 모두에게
ex)1차 당일=빨간색, 2차 3달=노란색

**Comment by vlaksuga** [comment]
중복 비정상 처리의 설정 권한은 owner에게 있다.
ip,  이름, 전화번호의 일치여부를 설정 기간 내에서 비교하고 판정하여 비정상 처리한다.
