### ISSUE TITLE
USER권한의 확장

### ISSUE THREAD

**Issue by vlaksuga** [vlaksuga/newcrm#6]
ASIS는 ADMIN, ACCOUNT의 구조였음.

TOBE에서 개선하고 싶은 방향이 있는가

**Comment by vlaksuga** [comment]
### USER ASIS
ADMIN
ACCOUNT

### USER TOBE 제안
ACCOUNT > USER 아님
같은 목적의 DB가 쌓이는 최소단위 CHANNEL이라고 재정의함. USER 아님

ADMIN : 최고관리자
AGENCY : CHANNEL에 대한 접근권을 가짐
BOSS : 광고 집행하시는 분 돈내는 분
TM : BOSS 밑에서 일하는 분

**Comment by mufasakang** [comment]
1. MBOss추가
-위치는 BOSS,TM 사이
-역할 : 팀장

**Comment by vlaksuga** [comment]
최종 권한 어카운트는
ADMIN
OWNER
AGENCY
MK
로 한다.
