### ISSUE TITLE
메모 및 DB처리에 관한 기능

### ISSUE THREAD

**Issue by vlaksuga** [vlaksuga/newcrm#8]
ASIS는 DB를 재가공하거나 메모를 삽입할 수 없었다.
JSON 컴퍼니의 경우 취급분류, 메모 기능을 사용하여 DB가 처리되는 것을 기록할 수 있었음
TOBE는 어떻게 이를 설정하면 좋을지 쓰시오

**Comment by mufasakang** [comment]
취급분류와 메모만 있으면 될것 같습니다

**Comment by vlaksuga** [comment]
취급 분류는 주문 조작으로 명명한다.

주문 조작 대상은 MK로 한정한다.
신규 주문 적재시
대기 : 주문이 대상에게 분배되기 이전상태
신규 : 분배가 완료된 상태
결번 : 없는 번호일때
부재 : 전화를 받지 않는 상태
본인아님 : 주문자와 번호가 불일치 할때
거절 : 결재의사가 없음이 분명할 때
가망 : 결재의사가 불분명 할 때
결재 : 결재시
로 나눈다
각 단계에서 메모를 삽입할 수 있고, 주문 조작 상태와 메모의 누적정보를 확인할 수 있다
