### ISSUE TITLE
정상/에러 처리 기능에 관하여

### ISSUE THREAD

**Issue by vlaksuga** [vlaksuga/newcrm#9]
ASIS는 정상DB와 에러DB라는 것이 구분되지 않아서 실질적 DB 측정에 어려움이 있었음
TOBE는 에러DB라는 기능을 추가시킨다고 했을 때
1. 자동으로 에러DB로 처리되는 경우를 정의한다.
2. 수동으로 에러DB로 처리할때 그 권한자가 누구인지 정한다.
3. 두명의 유저가 한 페이지에 접속한다고 가정할경우  시간차를 두고 에러DB와 정상DB 처리를 적용할 경우 이미 에러DB가 된 DB가 정상으로 돌아오는 것에 대하여 어떻게 처리할 지 정한다.

**Comment by mufasakang** [comment]
1. 에러 text를 미리 입력하여 그에 맞는 db를 제외한다.
-조건 : 2글자 이상 (ex개새,1818등)
2. BOSS 또는 MBOSS가 이의신청하고 AGENCY또는 AE가 컨펌을 한다
3. AGENCY또는 AE 중 한명만 에러처리가 가능하다 
-AGENCY:디폴트, AE:AGENCY가 없거나 권한을 가져올수 있음

**Comment by vlaksuga** [comment]
정상/에러 처리는
1. 중복 관리
2. 특별 주문관리로 나누어 관리하고
모두 OWNER가 설정 권한을 갖는다.
1. 중복관리는 IP, 이름, 전화번호를 설정 내에 삽입된 정보와 비교하여 판정한다.
2. 특별 주문관리는 그 외의 정보를 설정하여 사전에 에러 처리할 수 있다.
